name: Build snabbdom.js file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build Snabbdom
      shell: bash
      run: cd scripts && ./build-snabbdom.sh
    - uses: actions/upload-artifact@v4
      with:
        name: broccolini_snabbdom
        path: ./resin/res/snabbdom.js