name: Build PC tests for each JS backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu]
        library: [sdl2]
        engine: [quickjs, mujs]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.os }} w/ ${{ matrix.engine }}
      shell: bash
      run: BUILD_JS_TESTS=1 JS_ENGINE=${{ matrix.engine }} ./libs/chesto/helpers/build_pc.sh broccolini ${{ matrix.os }} ${{ matrix.library }}
    - name: Run tests
      shell: bash
      run: ./broccolini.bin