name: Build console apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: wiiu
            ext: wuhb
          - platform: switch
            ext: nro
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build Snabbdom (goes into app bundles)
      shell: bash
      run: cd scripts && ./build-snabbdom.sh
    - name: Build ${{ matrix.platform }}
      run: make ${{ matrix.platform }}
    - uses: actions/upload-artifact@v4
      with:
        name: broccolini.${{ matrix.ext }}
        path: /__w/broccolini/broccolini/broccolini.${{ matrix.ext }}